name: build

on:
  push:
    paths-ignore:
      - "**.md"
      - "**.bbcode"
      - LICENSE
      - .github/FUNDING.yml
    branches: [main, dev]
  pull_request:
    paths-ignore:
      - "**.md"
      - "**.bbcode"
      - LICENSE
      - .github/FUNDING.yml
    branches: [main]
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install build dependencies (apt)
        run: sudo apt install -y libx11-dev libxcursor-dev libpng-dev
        continue-on-error: false

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Caching yarn packages
        uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Set Up NodeJS 12.x
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - name: Caching pip packages
        uses: actions/cache@v2
        id: pip-cache # use this to check for `cache-hit` (`steps.pip-cache.outputs.cache-hit != 'true'`)
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/setup.py') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Generating `Bibata-Modern` symlinks
        run: cd svg && python link.py && cd ..
        continue-on-error: false

      - name: Generating `Bibata` Cursor Themes
        run: make WIN_SIZE=64
        continue-on-error: false

      - name: Compressing `Bibata-Modern` Unix Themes
        run: |
          tar -cvzf Bibata-Modern-Amber.tar.gz themes/Bibata-Modern-Amber
          tar -cvzf Bibata-Modern-Classic.tar.gz themes/Bibata-Modern-Classic
          tar -cvzf Bibata-Modern-Ice.tar.gz themes/Bibata-Modern-Ice

      - name: Uploading `Bibata-Modern-Amber` Unix Theme artifact
        uses: actions/upload-artifact@v2
        with:
          name: Bibata-Modern-Amber
          path: Bibata-Modern-Amber.tar.gz

      - name: Uploading `Bibata-Modern-Amber` Windows Theme artifact
        uses: actions/upload-artifact@v2
        with:
          name: Bibata-Modern-Amber-Windows
          path: themes/Bibata-Modern-Amber-Windows/*

      - name: Uploading `Bibata-Modern-Classic` Unix Theme artifact
        uses: actions/upload-artifact@v2
        with:
          name: Bibata-Modern-Classic
          path: Bibata-Modern-Classic.tar.gz

      - name: Uploading `Bibata-Modern-Classic` Windows Theme artifact
        uses: actions/upload-artifact@v2
        with:
          name: Bibata-Modern-Classic-Windows
          path: themes/Bibata-Modern-Classic-Windows/*

      - name: Uploading `Bibata-Modern-Ice` Unix Theme artifact
        uses: actions/upload-artifact@v2
        with:
          name: Bibata-Modern-Ice
          path: Bibata-Modern-Ice.tar.gz

      - name: Uploading `Bibata-Modern-Ice` Windows Theme artifact
        uses: actions/upload-artifact@v2
        with:
          name: Bibata-Modern-Ice-Windows
          path: themes/Bibata-Modern-Ice-Windows/*

      - name: Compressing `Bibata-Original` Unix Themes
        run: |
          tar -cvzf Bibata-Original-Amber.tar.gz themes/Bibata-Original-Amber
          tar -cvzf Bibata-Original-Classic.tar.gz themes/Bibata-Original-Classic
          tar -cvzf Bibata-Original-Ice.tar.gz themes/Bibata-Original-Ice

      - name: Uploading `Bibata-Original-Amber` Unix Theme artifact
        uses: actions/upload-artifact@v2
        with:
          name: Bibata-Original-Amber
          path: Bibata-Original-Amber.tar.gz

      - name: Uploading `Bibata-Original-Amber` Windows Theme artifact
        uses: actions/upload-artifact@v2
        with:
          name: Bibata-Original-Amber-Windows
          path: themes/Bibata-Original-Amber-Windows/*

      - name: Uploading `Bibata-Original-Classic` Unix Theme artifact
        uses: actions/upload-artifact@v2
        with:
          name: Bibata-Original-Classic
          path: Bibata-Original-Classic.tar.gz

      - name: Uploading `Bibata-Original-Classic` Windows Theme artifact
        uses: actions/upload-artifact@v2
        with:
          name: Bibata-Original-Classic-Windows
          path: themes/Bibata-Original-Classic-Windows/*

      - name: Uploading `Bibata-Original-Ice` Unix Theme artifact
        uses: actions/upload-artifact@v2
        with:
          name: Bibata-Original-Ice
          path: Bibata-Original-Ice.tar.gz

      - name: Uploading `Bibata-Original-Ice` Windows Theme artifact
        uses: actions/upload-artifact@v2
        with:
          name: Bibata-Original-Ice-Windows
          path: themes/Bibata-Original-Ice-Windows/*

      - name: Uploading `Bibata` bitmaps artifact
        uses: actions/upload-artifact@v2
        with:
          name: bitmaps
          path: bitmaps/*
